version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_PORT=5678
      - N8N_HOST=0.0.0.0
      - N8N_PROTOCOL=http
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_AUTH_EXCLUDE_ENDPOINTS=metrics,healthz,robots.txt
      - N8N_SECURITY_OAUTH2_LOGIN_ENABLED=false
      - N8N_SECURITY_PASSWORD_LOGIN_ENABLED=false
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: 